# uosc_danmaku 2.1.0
# Supported options only.

########
# Load #
########

auto_load=no
autoload_local_danmaku=yes
autoload_for_url=yes
#save_danmaku=no


###########
# Network #
###########

api_server=http://8.137.8.172:7768/api/v1/2NahgNwKzI1aXm0uX96P
fallback_server=https://fc.lyz05.cn
tmdb_api_key=MTU5MWU4MzVkNmI5MGY1NWYzNWIyNjhiMjE3NjA0ZWY=

#user_agent=mpv_danmaku/1.0
#proxy=127.0.0.1:7890
#cookie_file=


###########
# Display #
###########

vf_fps=yes
#fps=60/1.001
#merge_tolerance=-1
#opacity=0.7
#chConvert=0
#max_screen_danmaku=0


#########
# Style #
#########

scrolltime=15
fixtime=5
fontname=sans-serif
fontsize=40
shadow=0
bold=yes
displayarea=0.1
outline=1
#blacklist_path=


########
# Misc #
########

#history_path=~~/danmaku-history.json
#message_x=30
#message_y=30
#title_replace=
#excluded_path=
#open_search_danmaku_menu_key=Ctrl+d
#show_danmaku_keyboard_key=j
